#! /bin/sh

# Autostarts
sxhkd &
nitrogen --restore &
./.config/polybar/launch.sh &
picom --experimental-backends &
setxkbmap us,ru -option 'grp:win_space_toggle' &
xsetroot -cursor_name left_ptr &
dunst &
nm-applet &
./.config/bspwm/launch_kalu.sh &
udiskie --tray &
redshift-gtk &

# Workspaces setup
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Colors
bspc config normal_border_color		"#4c566a"
bspc config focused_border_color	"#5e81ac"
bspc config presel_feedback_color	"#5e81ac"

# Rules
bspc rule -a Emacs state=tiled
bspc rule -a Skype state=floating
bspc rule -a Qalculate-gtk state=floating
